# adapted from https://github.com/aws-samples/aws-batch-blueprints/blob/main/templates/batch-jq-ce-lt-local-ssd.yaml
# for Logan with c5d instances
#
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: '2010-09-09'
Description: Logan Analysis Cloudformation template for instances d

Parameters:
  InstanceTypes:
    Description: EC2 instance types
    Type: List<String>
    #Default: "c5d.4xlarge,c5d.9xlarge,c5d.12xlarge,c5d.18xlarge,c5d.24xlarge,c5d.metal"
    Default: "c5d"
  Minvcpus:
    Type: Number
    Default: 0
    Description: Minimum number of vCPUs per Compute Environment
  Maxvcpus:
    Type: Number
    Default: 10000 
    Description: Maximum number of vCPUs per Compute Environment
  EBSBootSize:
    Type: Number
    Default: 30
    Description: Size in GiB of EBS root volume

############################
## AWS Batch Infrastructure
Resources:
  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonElasticMapReduceFullAccess # for sdb
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore # for connecting to instance
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy # for https://github.com/aws-samples/aws-batch-blueprints/blob/main/templates/batch-jq-ce-lt-detailed-monitoring.yaml
  BatchInstancePolicy: # from https://github.com/aws-samples/aws-batch-blueprints/blob/main/templates/batch-jq-ce-lt-ebs-resize.yaml
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'BatchInstancePolicy-${AWS::StackName}'
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - ec2:CreateVolume
              - ec2:AttachVolume
              - ec2:ModifyVolume
              - ec2:DescribeVolumes
              - ec2:DescribeVolumesModifications
              - ec2:ModifyInstanceAttribute
              - logs:CreateLogGroup # for awslogs
              - dynamodb:UpdateItem
            Resource:
              - '*'
      Roles:
        - !Ref BatchInstanceRole
  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Ref: BatchInstanceRole
  SpotIamFleetRole: # taken from https://github.com/aodn/aws-wps/blob/master/wps-cloudformation-template.yaml
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: spot.amazonaws.com
            Action: sts:AssumeRole
          - Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole

  BatchLaunchTemplateDisques:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
          BlockDeviceMappings:
          - DeviceName: '/dev/xvda'
            Ebs:
              DeleteOnTermination: true
              Encrypted: false
              Iops: 3000
              VolumeSize: !Ref EBSBootSize
              VolumeType: 'gp3'
          UserData:
            Fn::Base64:
              !Sub |
                MIME-Version: 1.0
                Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

                --==MYBOUNDARY==
                Content-Type: text/x-shellscript; charset="us-ascii"

                #!/bin/bash

                exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

                yum install -y jq mdadm

                MOUNT_POINT="/localdisk"
                mkdir -p $MOUNT_POINT

                devices=`lsblk -o NAME -p -J | jq -r '.blockdevices[] | select(has("children") | not) | .name'`
                nb_devices=`echo $devices | tr ' ' '\n' | wc -l`

                if [[ $nb_devices > 1 ]]; then
                  yes | mdadm --create --verbose /dev/md0 --level=0 --raid-devices=$nb_devices $devices
                  mkfs.xfs /dev/md0
                  mount /dev/md0 $MOUNT_POINT
                else
                  mkfs.xfs $devices
                  mount $devices $MOUNT_POINT
                fi

                # brice's trick
                sysctl vm.dirty_writeback_centisecs=200
                sysctl vm.dirty_bytes=4294967296
                sysctl vm.dirty_background_bytes=2147483648
            
                --==MYBOUNDARY==--

  BatchECSCED:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        AllocationStrategy: SPOT_PRICE_CAPACITY_OPTIMIZED
        LaunchTemplate:
            LaunchTemplateId: !Ref BatchLaunchTemplateDisques
            Version: !GetAtt BatchLaunchTemplateDisques.LatestVersionNumber
        MinvCpus: !Ref Minvcpus
        MaxvCpus: !Ref Maxvcpus
        Type: SPOT 
        InstanceRole:
          Ref: BatchInstanceProfile
        InstanceTypes: !Ref InstanceTypes
        ImageId: ami-09f62d2604cc5b8fe # my custom Logan AMI (has awscliv2, mdadm) 
        Ec2KeyPair: "serratus"
        SpotIamFleetRole: !Ref SpotIamFleetRole
        Subnets: !Split [",", !ImportValue 'Logan-LargeScaleVPC-PrivateSubnets']
        Tags:
          Name: Logan-Analysis-SPOTD-1
        SecurityGroupIds:
        - !ImportValue 'Logan-LargeScaleVPC-SecurityGroup'
      ReplaceComputeEnvironment: false
      State: ENABLED

  BatchECSCED2:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        AllocationStrategy: SPOT_PRICE_CAPACITY_OPTIMIZED
        LaunchTemplate:
            LaunchTemplateId: !Ref BatchLaunchTemplateDisques
            Version: !GetAtt BatchLaunchTemplateDisques.LatestVersionNumber
        MinvCpus: !Ref Minvcpus
        MaxvCpus: !Ref Maxvcpus
        Type: SPOT 
        InstanceRole:
          Ref: BatchInstanceProfile
        InstanceTypes: !Ref InstanceTypes
        ImageId: ami-09f62d2604cc5b8fe # my custom Logan AMI (has awscliv2, mdadm) 
        Ec2KeyPair: "serratus"
        SpotIamFleetRole: !Ref SpotIamFleetRole
        Subnets: !Split [",", !ImportValue 'Logan-LargeScaleVPC-PrivateSubnets']
        Tags:
          Name: Logan-Analysis-SPOTD-2
        SecurityGroupIds:
        - !ImportValue 'Logan-LargeScaleVPC-SecurityGroup'
      ReplaceComputeEnvironment: false
      State: ENABLED

  BatchECSCED3:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        AllocationStrategy: SPOT_PRICE_CAPACITY_OPTIMIZED
        LaunchTemplate:
            LaunchTemplateId: !Ref BatchLaunchTemplateDisques
            Version: !GetAtt BatchLaunchTemplateDisques.LatestVersionNumber
        MinvCpus: !Ref Minvcpus
        MaxvCpus: !Ref Maxvcpus
        Type: SPOT 
        InstanceRole:
          Ref: BatchInstanceProfile
        InstanceTypes: !Ref InstanceTypes
        ImageId: ami-09f62d2604cc5b8fe # my custom Logan AMI (has awscliv2, mdadm) 
        Ec2KeyPair: "serratus"
        SpotIamFleetRole: !Ref SpotIamFleetRole
        Subnets: !Split [",", !ImportValue 'Logan-LargeScaleVPC-PrivateSubnets']
        Tags:
          Name: Logan-Analysis-SPOTD-3
        SecurityGroupIds:
        - !ImportValue 'Logan-LargeScaleVPC-SecurityGroup'
      ReplaceComputeEnvironment: false
      State: ENABLED

  BatchECSCED4:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeResources:
        AllocationStrategy: SPOT_PRICE_CAPACITY_OPTIMIZED
        LaunchTemplate:
            LaunchTemplateId: !Ref BatchLaunchTemplateDisques
            Version: !GetAtt BatchLaunchTemplateDisques.LatestVersionNumber
        MinvCpus: !Ref Minvcpus
        MaxvCpus: !Ref Maxvcpus
        Type: SPOT 
        InstanceRole:
          Ref: BatchInstanceProfile
        InstanceTypes: !Ref InstanceTypes
        ImageId: ami-09f62d2604cc5b8fe # my custom Logan AMI (has awscliv2, mdadm) 
        Ec2KeyPair: "serratus"
        SpotIamFleetRole: !Ref SpotIamFleetRole
        Subnets: !Split [",", !ImportValue 'Logan-LargeScaleVPC-PrivateSubnets']
        Tags:
          Name: Logan-Analysis-SPOTD-4
        SecurityGroupIds:
        - !ImportValue 'Logan-LargeScaleVPC-SecurityGroup'
      ReplaceComputeEnvironment: false
      State: ENABLED

  BatchJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: 'LoganAnalysisJobQueueDisques'
      ComputeEnvironmentOrder:
        - ComputeEnvironment: !Ref BatchECSCED
          Order: 1
        - ComputeEnvironment: !Ref BatchECSCED2
          Order: 2
        - ComputeEnvironment: !Ref BatchECSCED3
          Order: 3
      Priority: 1
      State: "ENABLED"

  LoganAnalysisOneCoreJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: 'logan-analysis-1c-job' 
      ContainerProperties:
        Image:
          Fn::Join:
          - ''
          - - Ref: AWS::AccountId
            - .dkr.ecr.
            - Ref: AWS::Region
            - ".amazonaws.com/logan-analysis-job-x86_64:latest"
        ResourceRequirements:
          - Type: MEMORY
            Value: "1500" # Vcpu/mem ratio of C5's
          - Type: VCPU
            Value: "1" 
        MountPoints:
          - ContainerPath: "/localdisk"
            ReadOnly: false
            SourceVolume: localdisk
        Volumes:
          - Name: localdisk
            Host:
              SourcePath: "/localdisk"
      RetryStrategy:
        Attempts: 5
        EvaluateOnExit:
          - OnStatusReason: "Host EC2*"
            Action: "RETRY"
          - OnReason: "*"
            Action: "EXIT"

  LoganAnalysisTwoCoresJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: 'logan-analysis-2c-job' 
      ContainerProperties:
        Image:
          Fn::Join:
          - ''
          - - Ref: AWS::AccountId
            - .dkr.ecr.
            - Ref: AWS::Region
            - ".amazonaws.com/logan-analysis-job-x86_64:latest"
        ResourceRequirements:
          - Type: MEMORY
            Value: "3000" # Vcpu/mem ratio of C5's
          - Type: VCPU
            Value: "2" 
        MountPoints:
          - ContainerPath: "/localdisk"
            ReadOnly: false
            SourceVolume: localdisk
        Volumes:
          - Name: localdisk
            Host:
              SourcePath: "/localdisk"
      RetryStrategy:
        Attempts: 5
        EvaluateOnExit:
          - OnStatusReason: "Host EC2*"
            Action: "RETRY"
          - OnReason: "*"
            Action: "EXIT"

  LoganAnalysisFourCoresJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: 'logan-analysis-4c-job' 
      ContainerProperties:
        Image:
          Fn::Join:
          - ''
          - - Ref: AWS::AccountId
            - .dkr.ecr.
            - Ref: AWS::Region
            - ".amazonaws.com/logan-analysis-job-x86_64:latest"
        ResourceRequirements:
          - Type: MEMORY
            Value: "6500" # Vcpu/mem ratio of C5's
          - Type: VCPU
            Value: "4"
        MountPoints:
          - ContainerPath: "/localdisk"
            ReadOnly: false
            SourceVolume: localdisk
        Volumes:
          - Name: localdisk
            Host:
              SourcePath: "/localdisk"
      RetryStrategy:
        Attempts: 5
        EvaluateOnExit:
          - OnStatusReason: "Host EC2*"
            Action: "RETRY"
          - OnReason: "*"
            Action: "EXIT"



#############
## Outputs ##
#############
Outputs:
  ComputeEnvironment:
    Value: !Ref BatchECSCED
  ComputeEnvironment:
    Value: !Ref BatchECSCED2
  ComputeEnvironment:
    Value: !Ref BatchECSCED3
  JobQueue:
    Value: !Ref BatchJobQueue
